# Generated by Django 3.0.6 on 2020-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('num', models.BigIntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
